// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package foodios

// schema: app.foodios.feed.recipePost

import util "github.com/bluesky-social/indigo/lex/util"

func init() {
	util.RegisterType("app.foodios.feed.recipePost", &FeedRecipePost{})
} //
// RECORDTYPE: FeedRecipePost
type FeedRecipePost struct {
	LexiconTypeID string `json:"$type,const=app.foodios.feed.recipePost" cborgen:"$type,const=app.foodios.feed.recipePost"`
	// createdAt: Client-declared timestamp when this post was originally created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
}
