// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package foodios

// schema: app.foodios.feed.defs

// FeedDefs_RecipeRevisionView is a "recipeRevisionView" in the app.foodios.feed.defs schema.
type FeedDefs_RecipeRevisionView struct {
	RevisionContent     *FeedRecipeRevision     `json:"revisionContent" cborgen:"revisionContent"`
	RevisionRefs        []*FeedDefs_RevisionRef `json:"revisionRefs" cborgen:"revisionRefs"`
	SelectedRevisionUri string                  `json:"selectedRevisionUri" cborgen:"selectedRevisionUri"`
}

// FeedDefs_RevisionRef is a "revisionRef" in the app.foodios.feed.defs schema.
type FeedDefs_RevisionRef struct {
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	Uri       string `json:"uri" cborgen:"uri"`
}
