// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package foodios

// schema: app.foodios.feed.reviewRating

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	appbskytypes "github.com/bluesky-social/indigo/api/bsky"
	"github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	//util.RegisterType("app.foodios.feed.reviewRating", &FeedReviewRating{})
} //
// RECORDTYPE: FeedReviewRating
type FeedReviewRating struct {
	LexiconTypeID string `json:"$type,const=app.foodios.feed.reviewRating" cborgen:"$type,const=app.foodios.feed.reviewRating"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// embed: Any images or videos attached to this review (image).
	Embed *FeedReviewRating_Embed `json:"embed,omitempty" cborgen:"embed,omitempty"`
	// labels: Self-label values for this post. Effectively content warnings.
	Labels *FeedReviewRating_Labels `json:"labels,omitempty" cborgen:"labels,omitempty"`
	// langs: Indicates human language of post primary text content.
	Langs []string `json:"langs,omitempty" cborgen:"langs,omitempty"`
	// reviewRating: Rating value from 1 to 10 (representing 1/2 to 5 stars).
	ReviewRating *int64                         `json:"reviewRating,omitempty" cborgen:"reviewRating,omitempty"`
	Subject      *comatprototypes.RepoStrongRef `json:"subject" cborgen:"subject"`
	// tags: Additional hashtags, in addition to any included in post text and facets.
	Tags []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	// text: The actual body of the review (reviewBody).
	Text *string `json:"text,omitempty" cborgen:"text,omitempty"`
}

// Any images or videos attached to this review (image).
type FeedReviewRating_Embed struct {
	EmbedImages *appbskytypes.EmbedImages
	EmbedVideo  *appbskytypes.EmbedVideo
}

func (t *FeedReviewRating_Embed) MarshalJSON() ([]byte, error) {
	if t.EmbedImages != nil {
		t.EmbedImages.LexiconTypeID = "app.bsky.embed.images"
		return json.Marshal(t.EmbedImages)
	}
	if t.EmbedVideo != nil {
		t.EmbedVideo.LexiconTypeID = "app.bsky.embed.video"
		return json.Marshal(t.EmbedVideo)
	}
	return nil, fmt.Errorf("cannot marshal empty enum")
}
func (t *FeedReviewRating_Embed) UnmarshalJSON(b []byte) error {
	typ, err := util.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.images":
		t.EmbedImages = new(appbskytypes.EmbedImages)
		return json.Unmarshal(b, t.EmbedImages)
	case "app.bsky.embed.video":
		t.EmbedVideo = new(appbskytypes.EmbedVideo)
		return json.Unmarshal(b, t.EmbedVideo)

	default:
		return nil
	}
}

func (t *FeedReviewRating_Embed) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.EmbedImages != nil {
		return t.EmbedImages.MarshalCBOR(w)
	}
	if t.EmbedVideo != nil {
		return t.EmbedVideo.MarshalCBOR(w)
	}
	return fmt.Errorf("cannot cbor marshal empty enum")
}
func (t *FeedReviewRating_Embed) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := util.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.images":
		t.EmbedImages = new(appbskytypes.EmbedImages)
		return t.EmbedImages.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.video":
		t.EmbedVideo = new(appbskytypes.EmbedVideo)
		return t.EmbedVideo.UnmarshalCBOR(bytes.NewReader(b))

	default:
		return nil
	}
}

// Self-label values for this post. Effectively content warnings.
type FeedReviewRating_Labels struct {
	LabelDefs_SelfLabels *comatprototypes.LabelDefs_SelfLabels
}

func (t *FeedReviewRating_Labels) MarshalJSON() ([]byte, error) {
	if t.LabelDefs_SelfLabels != nil {
		t.LabelDefs_SelfLabels.LexiconTypeID = "com.atproto.label.defs#selfLabels"
		return json.Marshal(t.LabelDefs_SelfLabels)
	}
	return nil, fmt.Errorf("cannot marshal empty enum")
}
func (t *FeedReviewRating_Labels) UnmarshalJSON(b []byte) error {
	typ, err := util.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.atproto.label.defs#selfLabels":
		t.LabelDefs_SelfLabels = new(comatprototypes.LabelDefs_SelfLabels)
		return json.Unmarshal(b, t.LabelDefs_SelfLabels)

	default:
		return nil
	}
}

func (t *FeedReviewRating_Labels) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.LabelDefs_SelfLabels != nil {
		return t.LabelDefs_SelfLabels.MarshalCBOR(w)
	}
	return fmt.Errorf("cannot cbor marshal empty enum")
}
func (t *FeedReviewRating_Labels) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := util.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "com.atproto.label.defs#selfLabels":
		t.LabelDefs_SelfLabels = new(comatprototypes.LabelDefs_SelfLabels)
		return t.LabelDefs_SelfLabels.UnmarshalCBOR(bytes.NewReader(b))

	default:
		return nil
	}
}
